{% set version="1.4" %}

build:
  number: 0

about:
  home: https://github.com/Kingsford-Group/squid
  license: BSD 3
  summary: Detector for fusion-gene and non-fusion-gene transcriptomic structural variations from RNA-seq data

package:
  name: squid
  version: {{ version }}

source:
  url: https://github.com/Kingsford-Group/squid/archive/v{{ version }}.tar.gz
  md5: 0786119db2ce764dc55fdb407e5ddd7b

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - boost
    - zlib
    - bamtools
    - glpk
  run:
    - boost
    - zlib
    - bamtools
    - glpk

test:
  commands:
    - squid --help
