{% set version = '0.1.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-geoaxe
  version: {{ version|replace("-", "_") }}

source:
  fn: geoaxe_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/geoaxe_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/geoaxe/geoaxe_{{ version }}.tar.gz
  sha256: 7ba4e5285670e67e307224222fcee5f7d6b67b6c1a5f7b8f34e64222d63c7e10



build:
  merge_build_host: True 
  number: 0
  noarch: generic

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
    - r-jsonlite
    - r-rgeos
    - r-sp

  run:
    - r-base
    - r-jsonlite
    - r-rgeos
    - r-sp

test:
  commands:
    - $R -e "library('geoaxe')"           
    - "\"%R%\" -e \"library('geoaxe')\"" 


about:
  home: https://github.com/ropenscilabs/geoaxe
  license: MIT + file LICENSE
  summary: Split 'geospatial' objects into pieces. Includes support for some spatial object inputs,
    'Well-Known Text', and 'GeoJSON'.
  license_family: MIT
